#!/bin/sh
# Start epics LTC2499 IOC

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin

case "$1" in
  start)
    echo -n "Starting LTC2499-ioc"
    export EPICS_HOST_ARCH=linux-arm
    export LD_LIBRARY_PATH=/opt/epics/base/lib/linux-arm
    cd /opt/LTC2499-ioc/iocBoot/iocLTC2499
    screen -d -m -S ioc /opt/LTC2499-ioc/bin/linux-arm/LTC2499 st.cmd
    echo "."
    ;;
  stop)
    echo -n "Stopping LTC2499-ioc"
    kill -9 `/bin/pidof /opt/LTC2499-ioc/bin/linux-arm/LTC2499`
    unset EPICS_HOST_ARCH
    echo "."
    ;;
  force-reload|restart)
    sh $0 stop
    sh $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/epics-LTC2499 {start|stop|restart|force-reload}"
    exit 1
    ;;
esac
